import { Button, Container, Grid, TextField } from "@mui/material";
import Head from "next/head";
import * as React from 'react';
import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import { useForm } from "react-hook-form";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <LoginAppBar />
        <Toolbar />
        <Container sx={{marginTop: '20px'}}>
          <LoginForm onLoginSuccess={() => {
            router.push('/admin/partners')
          }} />
        </Container>
      </div>
    </>
  );
}

function LoginForm ({onLoginSuccess}) {
  const {handleSubmit, register} = useForm<{
    username: string,
    password: string
  }>()
  return (
    <form onSubmit={handleSubmit((values) => {
      console.log(values)
      onLoginSuccess()
    })}>
      <Grid container gap={1}>
        <Grid item xs={12}>
          <TextField {...register('username')} fullWidth label="Usuario" />
        </Grid>
        <Grid item xs={12}>
          <TextField {...register('password')} fullWidth label="Contraseña" type="password" />
        </Grid>
        <Grid item xs={12} justifyContent={'flex-end'} display={'flex'} flexDirection={'row'}>
          <Button type="submit" variant={'contained'}>Acceder</Button>
        </Grid>
      </Grid>
    </form>
  )
}

function LoginAppBar() {
  return (
    <Box sx={{ flexGrow: 1 }}>
      <AppBar position="fixed">
        <Toolbar>
          <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
            Página de bienvenida
          </Typography>
        </Toolbar>
      </AppBar>
    </Box>
  );
}

/*

function AppBar() {
  return (
    <Box sx={{ flexGrow: 1 }}>
      <AppBar position="static">
        <Toolbar>
          <IconButton
            size="large"
            edge="start"
            color="inherit"
            aria-label="menu"
            sx={{ mr: 2 }}
          >
            <MenuIcon />
          </IconButton>
          <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
            News
          </Typography>
          <Button color="inherit">Login</Button>
        </Toolbar>
      </AppBar>
    </Box>
  );
}*/